# Generated by Django 4.1.6 on 2023-02-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='nom'),
        ),
    ]
